[book]
authors = ["Andrew Gauger"]
language = "en"
src = "src"
title = "AI for Good"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/AndyGauge/ai-for-good"

[build]
build-dir = "book"
